use crate::network::{AttributeTag, SpawnTrajectory};

#[inline(never)]
pub (crate) fn spawn_stats(obj: &str) -> Option<SpawnTrajectory> {
    match obj {
        "TAGame.Ball_Breakout_TA" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Ball.Ball_Breakout" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Ball.Ball_Trajectory" => Some(SpawnTrajectory::LocationAndRotation),
        "TAGame.Ball_TA" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Ball.Ball_BasketBall_Mutator" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Ball.Ball_BasketBall" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Ball.Ball_Basketball" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Ball.Ball_Default" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Ball.Ball_Puck" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Ball.Ball_Anniversary" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Ball.CubeBall" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Ball.Ball_Haunted" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Ball.Ball_Training" => Some(SpawnTrajectory::LocationAndRotation),
        "TAGame.Ball_Haunted_TA" => Some(SpawnTrajectory::LocationAndRotation),
        "TAGame.Car_Season_TA" => Some(SpawnTrajectory::LocationAndRotation),
        "TAGame.Car_TA" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.Car.Car_Default" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.GameEvent.GameEvent_Season:CarArchetype" => Some(SpawnTrajectory::LocationAndRotation),
        "Archetypes.SpecialPickups.SpecialPickup_HauntedBallBeam" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_Rugby" => Some(SpawnTrajectory::Location),
        "TAGame.CameraSettingsActor_TA" => Some(SpawnTrajectory::Location),
        "TAGame.CarComponent_Boost_TA" => Some(SpawnTrajectory::Location),
        "TAGame.CarComponent_Dodge_TA" => Some(SpawnTrajectory::Location),
        "TAGame.CarComponent_DoubleJump_TA" => Some(SpawnTrajectory::Location),
        "TAGame.CarComponent_FlipCar_TA" => Some(SpawnTrajectory::Location),
        "TAGame.CarComponent_Jump_TA" => Some(SpawnTrajectory::Location),
        "TAGame.GameEvent_Season_TA" => Some(SpawnTrajectory::Location),
        "TAGame.GameEvent_Soccar_TA" => Some(SpawnTrajectory::Location),
        "TAGame.GameEvent_SoccarPrivate_TA" => Some(SpawnTrajectory::Location),
        "TAGame.GameEvent_SoccarSplitscreen_TA" => Some(SpawnTrajectory::Location),
        "TAGame.GRI_TA" => Some(SpawnTrajectory::Location),
        "TAGame.PRI_TA" => Some(SpawnTrajectory::Location),
        "TAGame.SpecialPickup_BallCarSpring_TA" => Some(SpawnTrajectory::Location),
        "TAGame.SpecialPickup_BallFreeze_TA" => Some(SpawnTrajectory::Location),
        "TAGame.SpecialPickup_BallGravity_TA" => Some(SpawnTrajectory::Location),
        "TAGame.SpecialPickup_BallLasso_TA" => Some(SpawnTrajectory::Location),
        "TAGame.SpecialPickup_BallVelcro_TA" => Some(SpawnTrajectory::Location),
        "TAGame.SpecialPickup_Batarang_TA" => Some(SpawnTrajectory::Location),
        "TAGame.SpecialPickup_BoostOverride_TA" => Some(SpawnTrajectory::Location),
        "TAGame.SpecialPickup_GrapplingHook_TA" => Some(SpawnTrajectory::Location),
        "TAGame.SpecialPickup_HitForce_TA" => Some(SpawnTrajectory::Location),
        "TAGame.SpecialPickup_Swapper_TA" => Some(SpawnTrajectory::Location),
        "TAGame.SpecialPickup_Tornado_TA" => Some(SpawnTrajectory::Location),
        "TAGame.Team_Soccar_TA" => Some(SpawnTrajectory::Location),
        "Archetypes.CarComponents.CarComponent_Boost" => Some(SpawnTrajectory::Location),
        "Archetypes.CarComponents.CarComponent_Dodge" => Some(SpawnTrajectory::Location),
        "Archetypes.CarComponents.CarComponent_DoubleJump" => Some(SpawnTrajectory::Location),
        "Archetypes.CarComponents.CarComponent_FlipCar" => Some(SpawnTrajectory::Location),
        "Archetypes.CarComponents.CarComponent_Jump" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_Basketball" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_BasketballPrivate" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_BasketballSplitscreen" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_Breakout" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_Hockey" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_HockeyPrivate" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_HockeySplitscreen" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_Items" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_Season" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_Soccar" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_SoccarPrivate" => Some(SpawnTrajectory::Location),
        "Archetypes.GameEvent.GameEvent_SoccarSplitscreen" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_BallFreeze" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_BallGrapplingHook" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_BallLasso" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_BallSpring" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_BallVelcro" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_Batarang" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_BoostOverride" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_CarSpring" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_GravityWell" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_StrongHit" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_Swapper" => Some(SpawnTrajectory::Location),
        "Archetypes.SpecialPickups.SpecialPickup_Tornado" => Some(SpawnTrajectory::Location),
        "Archetypes.Teams.Team0" => Some(SpawnTrajectory::Location),
        "Archetypes.Teams.Team1" => Some(SpawnTrajectory::Location),
        "GameInfo_Basketball.GameInfo.GameInfo_Basketball:GameReplicationInfoArchetype" => Some(SpawnTrajectory::Location),
        "GameInfo_Breakout.GameInfo.GameInfo_Breakout:GameReplicationInfoArchetype" => Some(SpawnTrajectory::Location),
        "Gameinfo_Hockey.GameInfo.Gameinfo_Hockey:GameReplicationInfoArchetype" => Some(SpawnTrajectory::Location),
        "GameInfo_Items.GameInfo.GameInfo_Items:GameReplicationInfoArchetype" => Some(SpawnTrajectory::Location),
        "GameInfo_Season.GameInfo.GameInfo_Season:GameReplicationInfoArchetype" => Some(SpawnTrajectory::Location),
        "GameInfo_Soccar.GameInfo.GameInfo_Soccar:GameReplicationInfoArchetype" => Some(SpawnTrajectory::Location),
        "GameInfo_Tutorial.GameInfo.GameInfo_Tutorial:GameReplicationInfoArchetype" => Some(SpawnTrajectory::Location),
        "TAGame.Default__CameraSettingsActor_TA" => Some(SpawnTrajectory::Location),
        "TAGame.Default__PRI_TA" => Some(SpawnTrajectory::Location),
        "TheWorld:PersistentLevel.BreakOutActor_Platform_TA" => Some(SpawnTrajectory::Location),
        "TheWorld:PersistentLevel.CrowdActor_TA" => Some(SpawnTrajectory::Location),
        "TheWorld:PersistentLevel.CrowdManager_TA" => Some(SpawnTrajectory::Location),
        "TheWorld:PersistentLevel.InMapScoreboard_TA" => Some(SpawnTrajectory::Location),
        "TheWorld:PersistentLevel.VehiclePickup_Boost_TA" => Some(SpawnTrajectory::Location),
        "TAGame.HauntedBallTrapTrigger_TA" => Some(SpawnTrajectory::Location),
        "ProjectX.Default__NetModeReplicator_X" => Some(SpawnTrajectory::Location),
        "GameInfo_Tutorial.GameEvent.GameEvent_Tutorial_Aerial" => Some(SpawnTrajectory::Location),
        "Archetypes.Tutorial.Cannon" => Some(SpawnTrajectory::Location),
        _ => None,
    }
}

#[inline(never)]
pub (crate) fn attributes(obj: &str) -> Option<AttributeTag> {
    match obj {
        "Engine.Actor:bBlockActors" => Some(AttributeTag::Boolean),
        "Engine.Actor:bCollideActors" => Some(AttributeTag::Boolean),
        "Engine.Actor:bHidden" => Some(AttributeTag::Boolean),
        "Engine.Actor:DrawScale" => Some(AttributeTag::Float),
        "Engine.Actor:RemoteRole" => Some(AttributeTag::Enum),
        "Engine.Actor:Role" => Some(AttributeTag::Enum),
        "Engine.Actor:Rotation" => Some(AttributeTag::RotationTag),
        "Engine.GameReplicationInfo:bMatchIsOver" => Some(AttributeTag::Boolean),
        "Engine.GameReplicationInfo:GameClass" => Some(AttributeTag::Flagged),
        "Engine.GameReplicationInfo:ServerName" => Some(AttributeTag::String),
        "Engine.Pawn:PlayerReplicationInfo" => Some(AttributeTag::Flagged),
        "Engine.PlayerReplicationInfo:bBot" => Some(AttributeTag::Boolean),
        "Engine.PlayerReplicationInfo:bIsSpectator" => Some(AttributeTag::Boolean),
        "Engine.PlayerReplicationInfo:bReadyToPlay" => Some(AttributeTag::Boolean),
        "Engine.PlayerReplicationInfo:bTimedOut" => Some(AttributeTag::Boolean),
        "Engine.PlayerReplicationInfo:bWaitingPlayer" => Some(AttributeTag::Boolean),
        "Engine.PlayerReplicationInfo:Ping" => Some(AttributeTag::Byte),
        "Engine.PlayerReplicationInfo:PlayerID" => Some(AttributeTag::Int),
        "Engine.PlayerReplicationInfo:PlayerName" => Some(AttributeTag::String),
        "Engine.PlayerReplicationInfo:RemoteUserData" => Some(AttributeTag::String),
        "Engine.PlayerReplicationInfo:Score" => Some(AttributeTag::Int),
        "Engine.PlayerReplicationInfo:Team" => Some(AttributeTag::Flagged),
        "Engine.PlayerReplicationInfo:UniqueId" => Some(AttributeTag::UniqueId),
        "Engine.TeamInfo:Score" => Some(AttributeTag::Int),
        "ProjectX.GRI_X:bGameStarted" => Some(AttributeTag::Boolean),
        "ProjectX.GRI_X:GameServerID" => Some(AttributeTag::QWord),
        "ProjectX.GRI_X:MatchGUID" => Some(AttributeTag::String),
        "ProjectX.GRI_X:ReplicatedGameMutatorIndex" => Some(AttributeTag::Int),
        "ProjectX.GRI_X:ReplicatedGamePlaylist" => Some(AttributeTag::Int),
        "ProjectX.GRI_X:Reservations" => Some(AttributeTag::Reservation),
        "TAGame.Ball_Breakout_TA:AppliedDamage" => Some(AttributeTag::AppliedDamage),
        "TAGame.Ball_Breakout_TA:DamageIndex" => Some(AttributeTag::Int),
        "TAGame.Ball_Breakout_TA:LastTeamTouch" => Some(AttributeTag::Byte),
        "TAGame.Ball_TA:GameEvent" => Some(AttributeTag::Flagged),
        "TAGame.Ball_TA:HitTeamNum" => Some(AttributeTag::Byte),
        "TAGame.Ball_TA:ReplicatedAddedCarBounceScale" => Some(AttributeTag::Float),
        "TAGame.Ball_TA:ReplicatedBallMaxLinearSpeedScale" => Some(AttributeTag::Float),
        "TAGame.Ball_TA:ReplicatedBallScale" => Some(AttributeTag::Float),
        "TAGame.Ball_TA:ReplicatedExplosionData" => Some(AttributeTag::Explosion),
        "TAGame.Ball_TA:ReplicatedExplosionDataExtended" => Some(AttributeTag::ExtendedExplosion),
        "TAGame.Ball_TA:ReplicatedWorldBounceScale" => Some(AttributeTag::Float),
        "TAGame.BreakOutActor_Platform_TA:DamageState" => Some(AttributeTag::DamageState),
        "TAGame.CameraSettingsActor_TA:bUsingBehindView" => Some(AttributeTag::Boolean),
        "TAGame.CameraSettingsActor_TA:bMouseCameraToggleEnabled" => Some(AttributeTag::Boolean),
        "TAGame.CameraSettingsActor_TA:bUsingSecondaryCamera" => Some(AttributeTag::Boolean),
        "TAGame.CameraSettingsActor_TA:bUsingSwivel" => Some(AttributeTag::Boolean),
        "TAGame.CameraSettingsActor_TA:CameraPitch" => Some(AttributeTag::Byte),
        "TAGame.CameraSettingsActor_TA:CameraYaw" => Some(AttributeTag::Byte),
        "TAGame.CameraSettingsActor_TA:PRI" => Some(AttributeTag::Flagged),
        "TAGame.CameraSettingsActor_TA:ProfileSettings" => Some(AttributeTag::CamSettings),
        "TAGame.Car_TA:AddedBallForceMultiplier" => Some(AttributeTag::Float),
        "TAGame.Car_TA:AddedCarForceMultiplier" => Some(AttributeTag::Float),
        "TAGame.Car_TA:AttachedPickup" => Some(AttributeTag::Flagged),
        "TAGame.Car_TA:ClubColors" => Some(AttributeTag::ClubColors),
        "TAGame.Car_TA:ReplicatedDemolish" => Some(AttributeTag::Demolish),
        "TAGame.Car_TA:TeamPaint" => Some(AttributeTag::TeamPaint),
        "TAGame.CarComponent_Boost_TA:bNoBoost" => Some(AttributeTag::Boolean),
        "TAGame.CarComponent_Boost_TA:BoostModifier" => Some(AttributeTag::Float),
        "TAGame.CarComponent_Boost_TA:bUnlimitedBoost" => Some(AttributeTag::Boolean),
        "TAGame.CarComponent_Boost_TA:RechargeDelay" => Some(AttributeTag::Float),
        "TAGame.CarComponent_Boost_TA:RechargeRate" => Some(AttributeTag::Float),
        "TAGame.CarComponent_Boost_TA:ReplicatedBoostAmount" => Some(AttributeTag::Byte),
        "TAGame.CarComponent_Boost_TA:UnlimitedBoostRefCount" => Some(AttributeTag::Int),
        "TAGame.CarComponent_Dodge_TA:DodgeTorque" => Some(AttributeTag::Location),
        "TAGame.CarComponent_FlipCar_TA:bFlipRight" => Some(AttributeTag::Boolean),
        "TAGame.CarComponent_FlipCar_TA:FlipCarTime" => Some(AttributeTag::Float),
        "TAGame.CarComponent_TA:ReplicatedActive" => Some(AttributeTag::Byte),
        "TAGame.CarComponent_TA:ReplicatedActivityTime" => Some(AttributeTag::Float),
        "TAGame.CarComponent_TA:Vehicle" => Some(AttributeTag::Flagged),
        "TAGame.CrowdActor_TA:GameEvent" => Some(AttributeTag::Flagged),
        "TAGame.CrowdActor_TA:ModifiedNoise" => Some(AttributeTag::Float),
        "TAGame.CrowdActor_TA:ReplicatedCountDownNumber" => Some(AttributeTag::Int),
        "TAGame.CrowdActor_TA:ReplicatedOneShotSound" => Some(AttributeTag::Flagged),
        "TAGame.CrowdActor_TA:ReplicatedRoundCountDownNumber" => Some(AttributeTag::Int),
        "TAGame.CrowdManager_TA:GameEvent" => Some(AttributeTag::Flagged),
        "TAGame.CrowdManager_TA:ReplicatedGlobalOneShotSound" => Some(AttributeTag::Flagged),
        "TAGame.GameEvent_Soccar_TA:bBallHasBeenHit" => Some(AttributeTag::Boolean),
        "TAGame.GameEvent_Soccar_TA:bClubMatch" => Some(AttributeTag::Boolean),
        "TAGame.GameEvent_Soccar_TA:bOverTime" => Some(AttributeTag::Boolean),
        "TAGame.GameEvent_Soccar_TA:bUnlimitedTime" => Some(AttributeTag::Boolean),
        "TAGame.GameEvent_Soccar_TA:GameTime" => Some(AttributeTag::Int),
        "TAGame.GameEvent_Soccar_TA:ReplicatedMusicStinger" => Some(AttributeTag::MusicStinger),
        "TAGame.GameEvent_Soccar_TA:ReplicatedScoredOnTeam" => Some(AttributeTag::Byte),
        "TAGame.GameEvent_Soccar_TA:ReplicatedServerPerformanceState" => Some(AttributeTag::Byte),
        "TAGame.GameEvent_Soccar_TA:ReplicatedStatEvent" => Some(AttributeTag::StatEvent),
        "TAGame.GameEvent_Soccar_TA:RoundNum" => Some(AttributeTag::Int),
        "TAGame.GameEvent_Soccar_TA:SecondsRemaining" => Some(AttributeTag::Int),
        "TAGame.GameEvent_Soccar_TA:SeriesLength" => Some(AttributeTag::Int),
        "TAGame.GameEvent_Soccar_TA:SubRulesArchetype" => Some(AttributeTag::Flagged),
        "TAGame.GameEvent_SoccarPrivate_TA:MatchSettings" => Some(AttributeTag::PrivateMatchSettings),
        "TAGame.GameEvent_TA:bCanVoteToForfeit" => Some(AttributeTag::Boolean),
        "TAGame.GameEvent_TA:bHasLeaveMatchPenalty" => Some(AttributeTag::Boolean),
        "TAGame.GameEvent_TA:BotSkill" => Some(AttributeTag::Int),
        "TAGame.GameEvent_TA:GameMode" => Some(AttributeTag::GameMode),
        "TAGame.GameEvent_TA:MatchTypeClass" => Some(AttributeTag::Flagged),
        "TAGame.GameEvent_TA:ReplicatedGameStateTimeRemaining" => Some(AttributeTag::Int),
        "TAGame.GameEvent_TA:ReplicatedRoundCountDownNumber" => Some(AttributeTag::Int),
        "TAGame.GameEvent_TA:ReplicatedStateIndex" => Some(AttributeTag::Byte),
        "TAGame.GameEvent_TA:ReplicatedStateName" => Some(AttributeTag::Int),
        "TAGame.GameEvent_Team_TA:bForfeit" => Some(AttributeTag::Boolean),
        "TAGame.GameEvent_Team_TA:MaxTeamSize" => Some(AttributeTag::Int),
        "TAGame.GRI_TA:NewDedicatedServerIP" => Some(AttributeTag::String),
        "TAGame.PRI_TA:bIsInSplitScreen" => Some(AttributeTag::Boolean),
        "TAGame.PRI_TA:bMatchMVP" => Some(AttributeTag::Boolean),
        "TAGame.PRI_TA:bOnlineLoadoutSet" => Some(AttributeTag::Boolean),
        "TAGame.PRI_TA:bOnlineLoadoutsSet" => Some(AttributeTag::Boolean),
        "TAGame.PRI_TA:BotProductName" => Some(AttributeTag::Int),
        "TAGame.PRI_TA:bReady" => Some(AttributeTag::Boolean),
        "TAGame.PRI_TA:bUsingBehindView" => Some(AttributeTag::Boolean),
        "TAGame.PRI_TA:bUsingItems" => Some(AttributeTag::Boolean),
        "TAGame.PRI_TA:bUsingSecondaryCamera" => Some(AttributeTag::Boolean),
        "TAGame.PRI_TA:CameraPitch" => Some(AttributeTag::Byte),
        "TAGame.PRI_TA:CameraSettings" => Some(AttributeTag::CamSettings),
        "TAGame.PRI_TA:CameraYaw" => Some(AttributeTag::Byte),
        "TAGame.PRI_TA:ClientLoadout" => Some(AttributeTag::Loadout),
        "TAGame.PRI_TA:ClientLoadoutOnline" => Some(AttributeTag::LoadoutOnline),
        "TAGame.PRI_TA:ClientLoadouts" => Some(AttributeTag::TeamLoadout),
        "TAGame.PRI_TA:ClientLoadoutsOnline" => Some(AttributeTag::LoadoutsOnline),
        "TAGame.PRI_TA:ClubID" => Some(AttributeTag::Int64),
        "TAGame.PRI_TA:MatchAssists" => Some(AttributeTag::Int),
        "TAGame.PRI_TA:MatchBreakoutDamage" => Some(AttributeTag::Int),
        "TAGame.PRI_TA:MatchGoals" => Some(AttributeTag::Int),
        "TAGame.PRI_TA:MatchSaves" => Some(AttributeTag::Int),
        "TAGame.PRI_TA:MatchScore" => Some(AttributeTag::Int),
        "TAGame.PRI_TA:MatchShots" => Some(AttributeTag::Int),
        "TAGame.PRI_TA:MaxTimeTillItem" => Some(AttributeTag::Int),
        "TAGame.PRI_TA:PartyLeader" => Some(AttributeTag::PartyLeader),
        "TAGame.PRI_TA:PawnType" => Some(AttributeTag::Byte),
        "TAGame.PRI_TA:PersistentCamera" => Some(AttributeTag::Flagged),
        "TAGame.PRI_TA:PlayerHistoryKey" => Some(AttributeTag::PlayerHistoryKey),
        "TAGame.PRI_TA:PlayerHistoryValid" => Some(AttributeTag::Boolean),
        "TAGame.PRI_TA:ReplicatedGameEvent" => Some(AttributeTag::Flagged),
        "TAGame.PRI_TA:ReplicatedWorstNetQualityBeyondLatency" => Some(AttributeTag::Byte),
        "TAGame.PRI_TA:SteeringSensitivity" => Some(AttributeTag::Float),
        "TAGame.PRI_TA:SkillTier" => Some(AttributeTag::FlaggedByte),
        "TAGame.PRI_TA:TimeTillItem" => Some(AttributeTag::Int),
        "TAGame.PRI_TA:Title" => Some(AttributeTag::Int),
        "TAGame.PRI_TA:TotalXP" => Some(AttributeTag::Int),
        "TAGame.PRI_TA:PrimaryTitle" => Some(AttributeTag::Title),
        "TAGame.PRI_TA:SecondaryTitle" => Some(AttributeTag::Title),
        "TAGame.PRI_TA:SpectatorShortcut" => Some(AttributeTag::Int),
        "TAGame.RBActor_TA:bFrozen" => Some(AttributeTag::Boolean),
        "TAGame.RBActor_TA:bIgnoreSyncing" => Some(AttributeTag::Boolean),
        "TAGame.RBActor_TA:bReplayActor" => Some(AttributeTag::Boolean),
        "TAGame.RBActor_TA:ReplicatedRBState" => Some(AttributeTag::RigidBody),
        "TAGame.RBActor_TA:WeldedInfo" => Some(AttributeTag::Welded),
        "TAGame.SpecialPickup_BallFreeze_TA:RepOrigSpeed" => Some(AttributeTag::Float),
        "TAGame.SpecialPickup_BallVelcro_TA:AttachTime" => Some(AttributeTag::Float),
        "TAGame.SpecialPickup_BallVelcro_TA:bBroken" => Some(AttributeTag::Boolean),
        "TAGame.SpecialPickup_BallVelcro_TA:bHit" => Some(AttributeTag::Boolean),
        "TAGame.SpecialPickup_BallVelcro_TA:BreakTime" => Some(AttributeTag::Float),
        "TAGame.SpecialPickup_Targeted_TA:Targeted" => Some(AttributeTag::Flagged),
        "TAGame.Team_Soccar_TA:GameScore" => Some(AttributeTag::Int),
        "TAGame.Team_TA:ClubColors" => Some(AttributeTag::ClubColors),
        "TAGame.Team_TA:ClubID" => Some(AttributeTag::Int64),
        "TAGame.Team_TA:CustomTeamName" => Some(AttributeTag::String),
        "TAGame.Team_TA:GameEvent" => Some(AttributeTag::Flagged),
        "TAGame.Team_TA:LogoData" => Some(AttributeTag::Flagged),
        "TAGame.Vehicle_TA:bDriving" => Some(AttributeTag::Boolean),
        "TAGame.Vehicle_TA:bReplicatedHandbrake" => Some(AttributeTag::Boolean),
        "TAGame.Vehicle_TA:ReplicatedSteer" => Some(AttributeTag::Byte),
        "TAGame.Vehicle_TA:ReplicatedThrottle" => Some(AttributeTag::Byte),
        "TAGame.VehiclePickup_TA:bNoPickup" => Some(AttributeTag::Boolean),
        "TAGame.VehiclePickup_TA:ReplicatedPickupData" => Some(AttributeTag::Pickup),
        "TAGame.VehiclePickup_TA:NewReplicatedPickupData" => Some(AttributeTag::PickupNew),
        "TAGame.Ball_Haunted_TA:LastTeamTouch" => Some(AttributeTag::Byte),
        "TAGame.Ball_Haunted_TA:TotalActiveBeams" => Some(AttributeTag::Byte),
        "TAGame.Ball_Haunted_TA:DeactivatedGoalIndex" => Some(AttributeTag::Byte),
        "TAGame.Ball_Haunted_TA:ReplicatedBeamBrokenValue" => Some(AttributeTag::Byte),
        "TAGame.Ball_Haunted_TA:bIsBallBeamed" => Some(AttributeTag::Boolean),
        "TAGame.SpecialPickup_Rugby_TA:bBallWelded" => Some(AttributeTag::Boolean),
        "TAGame.Cannon_TA:Pitch" => Some(AttributeTag::Float),
        "TAGame.Cannon_TA:FireCount" => Some(AttributeTag::Byte),
        _ => None,
    }
}

#[inline(never)]
pub (crate) fn object_classes() -> Vec<(&'static str, &'static str)> {
    vec![
        ("Archetypes.Ball.Ball_BasketBall_Mutator", "TAGame.Ball_TA"),
        ("Archetypes.Ball.Ball_Basketball", "TAGame.Ball_TA"),
        ("Archetypes.Ball.Ball_BasketBall", "TAGame.Ball_TA"),
        ("Archetypes.Ball.Ball_Beachball", "TAGame.Ball_TA"),
        ("Archetypes.Ball.Ball_Breakout", "TAGame.Ball_Breakout_TA"),
        ("Archetypes.Ball.Ball_Default", "TAGame.Ball_TA"),
        ("Archetypes.Ball.Ball_Trajectory", "TAGame.Ball_TA"),
        ("Archetypes.Ball.Ball_Haunted", "TAGame.Ball_Haunted_TA"),
        ("Archetypes.Ball.Ball_Puck", "TAGame.Ball_TA"),
        ("Archetypes.Ball.Ball_Anniversary", "TAGame.Ball_TA"),
        ("Archetypes.Ball.CubeBall", "TAGame.Ball_TA"),
        ("Archetypes.Ball.Ball_Training", "TAGame.Ball_TA"),
        ("Archetypes.Car.Car_Default", "TAGame.Car_TA"),
        ("Archetypes.CarComponents.CarComponent_Boost", "TAGame.CarComponent_Boost_TA"),
        ("Archetypes.CarComponents.CarComponent_Dodge", "TAGame.CarComponent_Dodge_TA"),
        ("Archetypes.CarComponents.CarComponent_DoubleJump", "TAGame.CarComponent_DoubleJump_TA"),
        ("Archetypes.CarComponents.CarComponent_FlipCar", "TAGame.CarComponent_FlipCar_TA"),
        ("Archetypes.CarComponents.CarComponent_Jump", "TAGame.CarComponent_Jump_TA"),
        ("Archetypes.GameEvent.GameEvent_Basketball", "TAGame.GameEvent_Soccar_TA"),
        ("Archetypes.GameEvent.GameEvent_BasketballPrivate", "TAGame.GameEvent_SoccarPrivate_TA"),
        ("Archetypes.GameEvent.GameEvent_BasketballSplitscreen", "TAGame.GameEvent_SoccarSplitscreen_TA"),
        ("Archetypes.GameEvent.GameEvent_Breakout", "TAGame.GameEvent_Soccar_TA"),
        ("Archetypes.GameEvent.GameEvent_Hockey", "TAGame.GameEvent_Soccar_TA"),
        ("Archetypes.GameEvent.GameEvent_HockeyPrivate", "TAGame.GameEvent_SoccarPrivate_TA"),
        ("Archetypes.GameEvent.GameEvent_HockeySplitscreen", "TAGame.GameEvent_SoccarSplitscreen_TA"),
        ("Archetypes.GameEvent.GameEvent_Items", "TAGame.GameEvent_Soccar_TA"),
        ("Archetypes.GameEvent.GameEvent_Season:CarArchetype", "TAGame.Car_TA"),
        ("Archetypes.GameEvent.GameEvent_Season", "TAGame.GameEvent_Season_TA"),
        ("Archetypes.GameEvent.GameEvent_Soccar", "TAGame.GameEvent_Soccar_TA"),
        ("Archetypes.GameEvent.GameEvent_SoccarPrivate", "TAGame.GameEvent_SoccarPrivate_TA"),
        ("Archetypes.GameEvent.GameEvent_SoccarSplitscreen", "TAGame.GameEvent_SoccarSplitscreen_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_BallFreeze", "TAGame.SpecialPickup_BallFreeze_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_BallGrapplingHook", "TAGame.SpecialPickup_GrapplingHook_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_BallLasso", "TAGame.SpecialPickup_BallLasso_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_BallSpring", "TAGame.SpecialPickup_BallCarSpring_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_BallVelcro", "TAGame.SpecialPickup_BallVelcro_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_Batarang", "TAGame.SpecialPickup_Batarang_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_BoostOverride", "TAGame.SpecialPickup_BoostOverride_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_CarSpring", "TAGame.SpecialPickup_BallCarSpring_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_GravityWell", "TAGame.SpecialPickup_BallGravity_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_StrongHit", "TAGame.SpecialPickup_HitForce_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_Swapper", "TAGame.SpecialPickup_Swapper_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_Tornado", "TAGame.SpecialPickup_Tornado_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_HauntedBallBeam", "TAGame.SpecialPickup_HauntedBallBeam_TA"),
        ("Archetypes.SpecialPickups.SpecialPickup_Rugby", "TAGame.SpecialPickup_Rugby_TA"),
        ("Archetypes.Teams.Team0", "TAGame.Team_Soccar_TA"),
        ("Archetypes.Teams.Team1", "TAGame.Team_Soccar_TA"),
        ("GameInfo_Basketball.GameInfo.GameInfo_Basketball:GameReplicationInfoArchetype", "TAGame.GRI_TA"),
        ("GameInfo_Breakout.GameInfo.GameInfo_Breakout:GameReplicationInfoArchetype", "TAGame.GRI_TA"),
        ("Gameinfo_Hockey.GameInfo.Gameinfo_Hockey:GameReplicationInfoArchetype", "TAGame.GRI_TA"),
        ("GameInfo_Items.GameInfo.GameInfo_Items:GameReplicationInfoArchetype", "TAGame.GRI_TA"),
        ("GameInfo_Season.GameInfo.GameInfo_Season:GameReplicationInfoArchetype", "TAGame.GRI_TA"),
        ("GameInfo_Soccar.GameInfo.GameInfo_Soccar:GameReplicationInfoArchetype", "TAGame.GRI_TA"),
        ("GameInfo_Tutorial.GameInfo.GameInfo_Tutorial:GameReplicationInfoArchetype", "TAGame.GRI_TA"),
        ("GameInfo_Tutorial.GameEvent.GameEvent_Tutorial_Aerial", "TAGame.GameEvent_Tutorial_TA"),
        ("TAGame.Default__CameraSettingsActor_TA", "TAGame.CameraSettingsActor_TA"),
        ("TAGame.Default__PRI_TA", "TAGame.PRI_TA"),
        ("TheWorld:PersistentLevel.BreakOutActor_Platform_TA", "TAGame.BreakOutActor_Platform_TA"),
        ("TheWorld:PersistentLevel.CrowdActor_TA", "TAGame.CrowdActor_TA"),
        ("TheWorld:PersistentLevel.CrowdManager_TA", "TAGame.CrowdManager_TA"),
        ("TheWorld:PersistentLevel.InMapScoreboard_TA", "TAGame.InMapScoreboard_TA"),
        ("TheWorld:PersistentLevel.VehiclePickup_Boost_TA", "TAGame.VehiclePickup_Boost_TA"),
        ("Haunted_TrainStation_P.TheWorld:PersistentLevel.HauntedBallTrapTrigger_TA_1", "TAGame.HauntedBallTrapTrigger_TA"),
        ("Haunted_TrainStation_P.TheWorld:PersistentLevel.HauntedBallTrapTrigger_TA_0", "TAGame.HauntedBallTrapTrigger_TA"),
        ("Archetypes.Tutorial.Cannon", "TAGame.Cannon_TA")
    ]
}

#[inline(never)]
pub (crate) fn parent_class(obj: &str) -> Option<&'static str> {
    match obj {
        "Engine.Actor" => Some("Core.Object"),
        "Engine.GameReplicationInfo" => Some("Engine.ReplicationInfo"),
        "Engine.Info" => Some("Engine.Actor"),
        "Engine.Pawn" => Some("Engine.Actor"),
        "Engine.PlayerReplicationInfo" => Some("Engine.ReplicationInfo"),
        "Engine.ReplicationInfo" => Some("Engine.Info"),
        "Engine.TeamInfo" => Some("Engine.ReplicationInfo"),
        "ProjectX.GRI_X" => Some("Engine.GameReplicationInfo"),
        "ProjectX.Pawn_X" => Some("Engine.Pawn"),
        "ProjectX.PRI_X" => Some("Engine.PlayerReplicationInfo"),
        "TAGame.Ball_TA" => Some("TAGame.RBActor_TA"),
        "TAGame.CameraSettingsActor_TA" => Some("Engine.ReplicationInfo"),
        "TAGame.Car_Season_TA" => Some("TAGame.PRI_TA"),
        "TAGame.Car_TA" => Some("TAGame.Vehicle_TA"),
        "TAGame.CarComponent_Boost_TA" => Some("TAGame.CarComponent_TA"),
        "TAGame.CarComponent_Dodge_TA" => Some("TAGame.CarComponent_TA"),
        "TAGame.CarComponent_DoubleJump_TA" => Some("TAGame.CarComponent_TA"),
        "TAGame.CarComponent_FlipCar_TA" => Some("TAGame.CarComponent_TA"),
        "TAGame.CarComponent_Jump_TA" => Some("TAGame.CarComponent_TA"),
        "TAGame.CarComponent_TA" => Some("Engine.ReplicationInfo"),
        "TAGame.CrowdActor_TA" => Some("Engine.ReplicationInfo"),
        "TAGame.CrowdManager_TA" => Some("Engine.ReplicationInfo"),
        "TAGame.GameEvent_Season_TA" => Some("TAGame.GameEvent_Soccar_TA"),
        "TAGame.GameEvent_Soccar_TA" => Some("TAGame.GameEvent_Team_TA"),
        "TAGame.GameEvent_SoccarPrivate_TA" => Some("TAGame.GameEvent_Soccar_TA"),
        "TAGame.GameEvent_SoccarSplitscreen_TA" => Some("TAGame.GameEvent_SoccarPrivate_TA"),
        "TAGame.GameEvent_Tutorial_TA" => Some("TAGame.GameEvent_Soccar_TA"),
        "TAGame.GameEvent_TA" => Some("Engine.ReplicationInfo"),
        "TAGame.GameEvent_Team_TA" => Some("TAGame.GameEvent_TA"),
        "TAGame.GRI_TA" => Some("ProjectX.GRI_X"),
        "TAGame.InMapScoreboard_TA" => Some("Engine.Actor"),
        "TAGame.PRI_TA" => Some("ProjectX.PRI_X"),
        "TAGame.RBActor_TA" => Some("ProjectX.Pawn_X"),
        "TAGame.SpecialPickup_BallCarSpring_TA" => Some("TAGame.SpecialPickup_Spring_TA"),
        "TAGame.SpecialPickup_BallFreeze_TA" => Some("TAGame.SpecialPickup_Targeted_TA"),
        "TAGame.SpecialPickup_BallGravity_TA" => Some("TAGame.SpecialPickup_TA"),
        "TAGame.SpecialPickup_BallLasso_TA" => Some("TAGame.SpecialPickup_GrapplingHook_TA"),
        "TAGame.SpecialPickup_BallVelcro_TA" => Some("TAGame.SpecialPickup_TA"),
        "TAGame.SpecialPickup_Batarang_TA" => Some("TAGame.SpecialPickup_BallLasso_TA"),
        "TAGame.SpecialPickup_BoostOverride_TA" => Some("TAGame.SpecialPickup_Targeted_TA"),
        "TAGame.SpecialPickup_GrapplingHook_TA" => Some("TAGame.SpecialPickup_Targeted_TA"),
        "TAGame.SpecialPickup_HitForce_TA" => Some("TAGame.SpecialPickup_TA"),
        "TAGame.SpecialPickup_Spring_TA" => Some("TAGame.SpecialPickup_Targeted_TA"),
        "TAGame.SpecialPickup_Swapper_TA" => Some("TAGame.SpecialPickup_Targeted_TA"),
        "TAGame.SpecialPickup_TA" => Some("TAGame.CarComponent_TA"),
        "TAGame.SpecialPickup_Targeted_TA" => Some("TAGame.SpecialPickup_TA"),
        "TAGame.SpecialPickup_Tornado_TA" => Some("TAGame.SpecialPickup_TA"),
        "TAGame.SpecialPickup_Rugby_TA" => Some("TAGame.SpecialPickup_TA"),
        "TAGame.Team_Soccar_TA" => Some("TAGame.Team_TA"),
        "TAGame.Team_TA" => Some("Engine.TeamInfo"),
        "TAGame.Vehicle_TA" => Some("TAGame.RBActor_TA"),
        "TAGame.VehiclePickup_TA" => Some("Engine.ReplicationInfo"),
        "TAGame.VehiclePickup_Boost_TA" => Some("TAGame.VehiclePickup_TA"),
        "TAGame.SpecialPickup_HauntedBallBeam_TA" => Some("TAGame.SpecialPickup_TA"),
        "TAGame.Cannon_TA" => Some("Engine.Actor"),
        _ => None,
    }
}
